# Generated by Django 5.0.6 on 2026-05-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='associated_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная приятная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Приятная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение (текст)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(default=120, verbose_name='Время на выполнение (в секундах)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Действие (что сделать)'),
        ),
    ]
