# Generated by Django 5.0.6 on 2026-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_habit_associated_habit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
    ]
