# Generated by Django 5.0.6 on 2026-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена сегодня'),
        ),
    ]
