# Generated by Django 5.0.6 on 2026-05-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_to_complete',
        ),
    ]
